{{--
    Printable report letterhead — shared by every module that prints.

    Renders, in order: the business letterhead (partials.business_header, from
    per-account Settings), the app name, the report title + optional subtitle,
    and a metadata strip (caller-supplied entries such as fiscal period and
    filters, always followed by Generated date/time and Generated By).

    Table-based layout with inline styles so it renders identically in browser
    print AND inside Dompdf (no flex/grid).

    Props:
      title      (required) — report name, e.g. __('messages.income_statement_title')
      subtitle   — optional secondary line (period dates, property scope…)
      meta       — ['Label' => 'value', …] metadata cells (fiscal period, filters…)
      landscape  — print this document on A4 landscape (wide/many-column reports)
      screen     — also show on screen; standalone print-preview documents pass
                   this. Inside the app layouts it defaults to print-only.
--}}
@props(['title', 'subtitle' => null, 'meta' => [], 'landscape' => false, 'screen' => false])

@php
    $metaCells = array_filter(
        $meta + [
            __('messages.generated') => now()->format('d M Y · h:i A'),
            __('messages.generated_by') => auth()->user()?->name,
        ],
        fn ($v) => $v !== null && $v !== ''
    );
@endphp

<div {{ $attributes->class(['print-only' => ! $screen]) }}>
    @include('partials.business_header')

    <div style="text-align:center; margin:0 0 12px;">
        <div style="font-size:10px; color:#6b7280; text-transform:uppercase; letter-spacing:0.08em;">{{ __('messages.apartment_management_system') }}</div>
        <div style="font-size:16px; font-weight:700; color:#111827; margin-top:2px;">{{ $title }}</div>
        @if($subtitle)
            <div style="font-size:11px; color:#6b7280; margin-top:2px;">{{ $subtitle }}</div>
        @endif
    </div>

    @if(count($metaCells))
        <table style="width:100%; border-collapse:collapse; border:1px solid #e5e7eb; margin-bottom:14px;">
            <tr>
                @foreach($metaCells as $label => $value)
                    <td style="padding:6px 10px; vertical-align:top; {{ $loop->last ? '' : 'border-right:1px solid #e5e7eb;' }}">
                        <div style="font-size:9px; color:#6b7280; font-weight:600; text-transform:uppercase; letter-spacing:0.05em;">{{ $label }}</div>
                        <div style="font-size:11px; color:#111827; font-weight:600; margin-top:1px;">{{ $value }}</div>
                    </td>
                @endforeach
            </tr>
        </table>
    @endif
</div>

@if($landscape)
    {{-- Overrides print.css's default A4 portrait; must come after it in the DOM. --}}
    <style media="print">
        @page { size: A4 landscape; }
    </style>
@endif
